name: Build OWASP ModSecurity Rules for OpenResty

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-modsecurity-rules:
    runs-on: ubuntu-latest
    container:
      # 关键修改点：使用包含编译工具的 fat 镜像
      image: openresty/openresty:alpine-fat
      options: --cap-add=SYS_PTRACE --volume ${{ github.workspace }}:/github/workspace

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install basic tools
      run: |
        # 精简依赖安装（fat 镜像已包含构建工具）
        apk add --no-cache \
          wget \
          unzip \
          git

    - name: Download OWASP CRS
      run: |
        CRS_VERSION="3.3.4"
        wget -qO crs.zip https://github.com/coreruleset/coreruleset/archive/refs/tags/v${CRS_VERSION}.zip
        unzip crs.zip -d /etc/modsecurity/
        mv /etc/modsecurity/coreruleset-${CRS_VERSION} /etc/modsecurity/crs
        rm crs.zip

    - name: Configure ModSecurity
      run: |
        # 确认 ModSecurity 模块已存在
        ls -l /usr/local/openresty/nginx/modules/ngx_http_modsecurity_module.so

        cat <<EOF > /etc/modsecurity/modsecurity.conf
        SecRuleEngine DetectionOnly
        SecAuditLog /var/log/modsec_audit.log
        SecAuditLogFormat JSON
        SecAuditLogType Serial
        SecDebugLog /var/log/modsec_debug.log
        SecDebugLogLevel 0
        Include /etc/modsecurity/crs/crs-setup.conf
        Include /etc/modsecurity/crs/rules/*.conf
        EOF

        # 应用自定义补丁（如果存在）
        if [ -f ./custom_rules.patch ]; then
          patch -d /etc/modsecurity/crs -p1 < ./custom_rules.patch
        fi

    - name: Validate configuration
      run: |
        mkdir -p /var/log/nginx/modsec
        touch /var/log/modsec_audit.log

        # 生成测试配置（直接使用镜像中的模块路径）
        cat <<EOF > /tmp/nginx-test.conf
        load_module /usr/local/openresty/nginx/modules/ngx_http_modsecurity_module.so;
        
        events {}
        http {
            modsecurity on;
            modsecurity_rules_file /etc/modsecurity/modsecurity.conf;
            
            server {
                listen 8080;
                location / {
                    modsecurity_rules off;
                    return 200 "Config Test OK";
                }
            }
        }
        EOF

        # 关键验证：测试配置文件
        nginx -t -c /tmp/nginx-test.conf

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: modsecurity-rules
        path: |
          /etc/modsecurity/crs/
          /etc/modsecurity/modsecurity.conf
        retention-days: 7
