name: ModSecurity CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  MODSEC_VERSION: "v3.0.11"          # ModSecurity 核心版本
  MODSEC_NGINX_VERSION: "v1.0.3"     # Nginx 连接器版本
  CRS_VERSION: "3.3.4"               # OWASP 规则版本
  DOCKER_IMAGE: "your-dockerhub-username/openresty-modsec-alpine"  # 镜像名称

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU (Multi-Arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            MODSEC_VERSION=${{ env.MODSEC_VERSION }}
            MODSEC_NGINX_VERSION=${{ env.MODSEC_NGINX_VERSION }}
            CRS_VERSION=${{ env.CRS_VERSION }}
